name = "bulmacast"
description = "A podcast-oriented theme for Hugo based on Bulma CSS framework"

homepage = "https://github.com/Alroniks/bulmacast"

license = "MIT"
licenselink = "https://github.com/Alroniks/bulmacast/blob/master/LICENSE.md"

# todo: need to learn examples add proper
tags = ["podcast", "responsive"]
# todo: need to learn examples add proper
features = ["Podcast RSS"]

theme_version = "0.1.0"

[author]
  name = "Ivan Klimchuk"
  homepage = "https://klimchuk.com"
